[package]
name = "skribli-mobile"
version = "0.0.2"
description = "Private Android Skrib and reminder companion"
authors = ["Ankit Bhardwaj"]
edition = "2021"

[lib]
name = "skribli_mobile_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
